// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqsrwywdwqxebiglkmit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxc3J3eXdkd3F4ZWJpZ2xrbWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTQxMjEsImV4cCI6MjA2NjY5MDEyMX0.Jlim1TpLbv2kZOzuiukKoTql5OjZ6md13AqI6zmi7jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);